server:
  port: 8080
spring:
  application:
    name: pocmicro
  web:
    resources:
      static-locations: classpath:/static/, classpath:/api-docs/
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - url: /openapi/cars.yml
        name: Cars Api